// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzt8-tCQWslYtbDIpyjymba1ioB9mSRj0',
    appId: '1:691378528376:web:92950413d3f5579bfa0d8d',
    messagingSenderId: '691378528376',
    projectId: 'mindfullday',
    authDomain: 'mindfullday.firebaseapp.com',
    storageBucket: 'mindfullday.appspot.com',
    measurementId: 'G-1NMMXSY5WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF5DJ1aT5q6kx00OznID7EwhVH5XsmHjg',
    appId: '1:691378528376:android:dd3396b6f80712d4fa0d8d',
    messagingSenderId: '691378528376',
    projectId: 'mindfullday',
    storageBucket: 'mindfullday.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg0opMgo07ISq4sFjkQcQcZLfgnAGna3w',
    appId: '1:691378528376:ios:ed56498664594088fa0d8d',
    messagingSenderId: '691378528376',
    projectId: 'mindfullday',
    storageBucket: 'mindfullday.appspot.com',
    iosBundleId: 'com.example.mindfulldayV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg0opMgo07ISq4sFjkQcQcZLfgnAGna3w',
    appId: '1:691378528376:ios:51a853a2a9c45c08fa0d8d',
    messagingSenderId: '691378528376',
    projectId: 'mindfullday',
    storageBucket: 'mindfullday.appspot.com',
    iosBundleId: 'com.example.mindfulldayV1.RunnerTests',
  );
}
